# Base configs
baseurl: "https://manishasardiwal.github.io/artwork/"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Artwork by Manisha Sardiwal"
subtitle: "See the world through my eyes!"
author: "Manisha Sardiwal"
header:
 title: "Artwork"
 subtitle: "by Manisha Sardiwal"
footer:
 name: "Hey there, my name is Manisha"
 bio: "I am a fashion designer from Jaipur,India. Having completed a fashion design
       diploma from INIFD, now I draw fashion illustrations and portraits. Feel free to 
       contact me for  any collaborations."
      
      
social_urls:
#   facebook: "https://www.facebook.com/ramswaroop"
#   twitter: "https://www.twitter.com/ram__patra"
  instagram: "https://www.instagram.com/_samsaraa/"
#   dribbble: "https://dribbble.com/rampatra"
#   linkedin: "https://in.linkedin.com/in/ram-patra"
#   github: "https://www.github.com/rampatra"
